### ISSUE TITLE
MAFF support

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla-plugins#14]
Mozilla Archive Format

http://maf.mozdev.org/
https://addons.mozilla.org/en-US/firefox/search/?q=maf
https://addons.mozilla.org/en-US/firefox/addon/mozilla-archive-format/

**Comment by azzamsa** [comment]
so what is the last status of "save page as MHTML or MAFF"? 

- it is not suppoerted feature due to qtwebkit does not support it yet.
- and to do such that thing, we can use "Webpage Saver: You can already do this via File -> Save page screen" ?

//duplicate in 
[#820](https://github.com/QupZilla/qupzilla/issues/820)
[#1158](https://github.com/QupZilla/qupzilla/issues/1158)
[#1309](https://github.com/QupZilla/qupzilla/issues/1309)
